### ISSUE TITLE
推广过于严重

### ISSUE THREAD

**Issue by jev001** [JoeyBling/ibooks#23]
您好
   之前通过webkettle项目 关注了您的gitee
   随后发现, 在您的博客上以及留言中发现了很多您的个人推广链接. 是有多么 ~~饥渴~~ 想让人知道您?
   并且您博客上所写的开源项目中, 存在多个滥用开源项目的痕迹. 
   望周知

**Comment by JoeyBling** [comment]
1. 那些链接都是编辑好复制来复制去的，我本身没太注意，可能你想多了
2. 既然是开源项目，不就是给其他人研究弄的吗，再说了我也没有用作商业用途

我本身没想太多，只是看到一些感兴趣的项目或者其他的东西都会接触下，有可能是我自己不太注意吧。我也不知道这么回事。你不喜欢可以不看，

**Comment by jev001** [comment]
您说的是

**Comment by JoeyBling** [comment]
> 您说的是

我也没别的意思，道德方面的问题我也没有触犯，可能自己平时没太注意这方面的问题，写`Markdown`的时候开头和结尾一般都是复制通用的，所以可能就是会出现你提到的问题。
- 但是无可否认的是国内侵权也是很严重的，我既然是原作者都不敢贴上自己的信息，这不是助长了盗版的人心理吗？

而且有些时候我也在测试一些评论插件是否可用，所以随手复制了一段内容，只是做一些推荐链接而已，方便一些初识的人能快速找到而已
